name: Kon
version: ${project.version}
main: me.misz.kon.Kon
api-version: 1.21
commands:
  kon:
    description: Przywołaj swojego konia jak w Wiedźminie 3
    usage: /<command> [help|get|reload]
    permission: kon.use
permissions:
  kon.use:
    description: pozwala używać /kon get i /kon help
    default: op
  kon.admin:
    description: pozwala używać /kon reload
    default: op
